InputDirectory: .
BaseURL: https://example.com
CodeStyle: "dracula" # Read about available themes here: https://github.com/alecthomas/chroma/tree/master/styles
OGImageConfig:
  IconPath: "./og/icon.jpg"
  FontPath: "./og/regular.ttf"
  FontSize: 92
